# Generated by Django 4.1.2 on 2023-02-21 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_point_lat_alter_point_long_alter_valve_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='valve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='api.valve'),
        ),
    ]
