# Generated by Django 4.1.7 on 2023-02-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_point_distance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='Tree',
        ),
    ]
